### ISSUE TITLE
SubHandlers not working with netstring based

### ISSUE THREAD

**Issue by jwasys** [medialab/txjsonrpc#1]
analisys:
BaseSubhandler does not get initialized from JSONRPC child class.

fix:
Add
BaseSubhandler.**init**(self) on line 38 in "txjsonrpc\netstring\jsonrpc.py"

trace:
exceptions.AttributeError: Example instance has no attribute 'subHandlers'

Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(_args,__kw)
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 1067, in doRead
    protocol = self.factory.buildProtocol(self._buildAddr(addr))
  File "C:\Python27\lib\site-packages\txjson_rpc-0.3.1-py2.7.egg\txjsonrpc\netstring\jsonrpc.py", line 165, in buildProtocol
    p.putSubHandler(key, klass(_args, **kws))
  File "C:\Python27\lib\site-packages\txjson_rpc-0.3.1-py2.7.egg\txjsonrpc\jsonrpc.py", line 19, in putSubHandler
    self.subHandlers[prefix] = handler
exceptions.AttributeError: Example instance has no attribute 'subHandlers'

**Comment by boogheta** [comment]
Apologies but this repository is not maintained by anyone, it is only a hardcopy of a version of https://github.com/oubiwann/txjsonrpc
You should rather use this other repo and file issues over there, thanks
